<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>fm350tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Backend\**\*.cs" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
</Project>
